content/ourteam.html

* Removed featured employee div (Carrie)
* Moved Carrie into a regular profile
* Sorted everyone alphabetically (last name)
* Changed some job titles

Team page patch

---

content/ourteam.html

Fixing typo in Carrie's job title

---

README.md

Adding how to deploy info to readme

---

themes/digitalservices/static/assets/wff-submission.html

Created a template ([based on formio's default](https://pro.formview.io/assets/email.html)) for form.io to send acknowledgement of application to business owner.

Acknowledgement of WFF application email template

---

themes/digitalservices/static/assets/minigrant.html

Template for minigrant email confirmation.
Use case: when applicant for OEWD mini-grant completes application they will receive an email based on this template, and an attached PDF with their info.

Adding email template for minigrant

---

content/_index.html

Changing civicmakers link to new surveymonkey link

---

themes/digitalservices/static/assets/shared_spaces.html

-added static shared spaces template
-converted from Brian's google doc: https://docs.google.com/document/d/1UUp8j4dOzDK3YReKJcV3-LorKHXeFXTccQaaYdCIDF0/edit#

Sharedspacetemplate

---

themes/digitalservices/static/assets/streetclosures.html

email template for Shared Spaces- street closures form

Created streetclosures.html

---

themes/digitalservices/static/assets/shared_spaces.html

- pulled out line for 4 days 
- made other line for all parking lanes
https://trello.com/c/7an77oII

update per trello card

---

themes/digitalservices/static/assets/shared_spaces.html

-added link to permit in email

permit link

---

themes/digitalservices/static/assets/streetclosures.html

https://trello.com/c/vy5o5jlb/35-add-paragraph-to-street-closures-confirmation-email-template

paragraph change to email template

---

content/joinus.html

* Removed inaccurate sentence about hiring horizon and positions

Updated jobs page

---

themes/digitalservices/static/assets/entertainment.html

Email template for entertainment commission: https://docs.google.com/document/d/1e47X4c4qAey2aBlCHrFXl5ytmTcaX0K25idpx_C0Ejs/edit#

entertainment commission email template

---

themes/digitalservices/static/assets/shared_spaces.html
themes/digitalservices/static/assets/streetclosures.html

permit tracker link
https://trello.com/c/SxJPq4Gj/76-confirmation-email-edits

tracker confirmation email edits 

---

themes/digitalservices/static/assets/entertainment.html

https://trello.com/c/npoeUQpo/82-entertainment-confirmation-email-change-to-address-formio-bug

remove line because of pdf bug 

---

themes/digitalservices/static/assets/sfshines.html

https://trello.com/c/zj7pYsCV/13-sf-shines-for-reopening-confirmation-email

sf shines email template

---

themes/digitalservices/static/assets/otc.html

Uploading content for email template for OTC project.

Adding email template for DBI OTC

---

themes/digitalservices/static/assets/ss_equity_grant.html

https://sfgov1-my.sharepoint.com/:w:/r/personal/robin_abad_sfgov_org/_layouts/15/doc2.aspx?sourcedoc=%7B33d2e7fb-fe5a-4585-96a4-524144367593%7D&action=view&wdLOR=c84A192CC-6EAC-6D4F-BCFD-1595F91DE926&wdAccPdf=0&wdparaid=15A3833A&cid=34b2fc87-1684-4f5b-87d4-32d79258c6d1

shared spaces equity grant email template

---

themes/digitalservices/static/assets/proph_eligibility.html

https://sfgovdt.jira.com/browse/ER-66

ER-66 New business and DBA name showing up on Submission form

---

themes/digitalservices/static/assets/proph_eligibility.html

Added white inline styling to CTA button and fixed address to only show up if BAN was provided.
https://sfgovdt.jira.com/browse/ER-73
https://sfgovdt.jira.com/browse/ER-66

ER-73 CTA is blue, also fix address text bug surfaced in ER-66

---

content/joinus.html
themes/digitalservices/static/css/styles.css

- Equity Statement
- Update page title to "Join our team"

Adding Equity Statement to Join Us page

---

themes/digitalservices/static/assets/entertainment_grant.html

https://docs.google.com/document/d/1iTcYFgAep5v2he04gDcrnmlN3ZGmtbCp43zrgXFG67Y/edit#

entertainment equity email

---

themes/digitalservices/static/assets/storefront_grant.html

https://docs.google.com/document/d/1Ae0qgM614nJY9Y0FVV6ySpSan8fgWmmGWg7GSqPgFYY/edit#

ER-96 Draft Submit your documents confirmation email

---

themes/digitalservices/static/assets/groupvaccine.html

So that formio submission data shows up in a different table.

Moving formio content table to outside of the table view

---

content/ourteam.html

Removed 4 team members: Brian, Christine L, Christina W, and James W

Remove Brian, Christine L, Christina W, James Wills

---

content/joinus.html

Added the link for the new platform PMs position to the Join us page. 
To review, check out the join us page on the review app, and make sure that both of the jobs links work.

Add platforms PM to join us page

---

content/strategy.html
themes/digitalservices/layouts/partials/header.html

* Added `redirect_url` as part of the template
* Set `redirect_url` on the strategy page to redirect to the appropriate sf.gov page

Redirect strategy page
